version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=374387630610.dkr.ecr.us-east-1.amazonaws.com/demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=demo:latest
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t demo:latest .
      - docker tag demo:latest 374387630610.dkr.ecr.us-east-1.amazonaws.com/demo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 374387630610.dkr.ecr.us-east-1.amazonaws.com/demo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"test-cluster","imageUri":"%s"}]' 374387630610.dkr.ecr.us-east-1.amazonaws.com/demo:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json